config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  root 'resumes#index'
  resources :resumes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/resume.rb
class Resume < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  before_action :set_resume, only: [:show, :edit, :update, :destroy]

  # GET /resumes
  # GET /resumes.json
  def index
    @resumes = Resume.all
    # HardWorker.my_method_async
    # HardWorker.a_my_method_async
    # MyWorker.my_method_async(third)
  end

  # GET /resumes/1
  # GET /resumes/1.json
  def show
  end

  # GET /resumes/new
  def new
    @resume = Resume.new
  end

  # GET /resumes/1/edit
  def edit
  end

  # POST /resumes
  # POST /resumes.json
  def create
    @resume = Resume.new(resume_params)

    respond_to do |format|
      if @resume.save
        format.html { redirect_to @resume, notice: '创建成功' }
        format.json { render :show, status: :created, location: @resume }
      else
        format.html { render :new }
        format.json { render json: @resume.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /resumes/1
  # PATCH/PUT /resumes/1.json
  def update
    respond_to do |format|
      if @resume.update(resume_params)
        format.html { redirect_to @resume, notice: '更新成功' }
        format.json { render :show, status: :ok, location: @resume }
      else
        format.html { render :edit }
        format.json { render json: @resume.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /resumes/1
  # DELETE /resumes/1.json
  def destroy
    @resume.destroy
    respond_to do |format|
      format.html { redirect_to resumes_url, notice: '删除成功' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_resume
      @resume = Resume.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def resume_params
      params.require(:resume).permit(:personality, :graduation_time, :familiar_frame, :apply, :position, :project_experience, :self_evaluation, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ResumeManagment</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <%= render file: 'layouts/header' %>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/header.html.erb
<!DOCTYPE html>
<html>
  <div class="header">
    <h1>简历</h1>
  </div>
</html>

app/views/resumes/_form.html.erb
<%= simple_form_for(resume) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :personality%>
    <%= f.input :graduation_time, as: :date %>
    <%= f.input :familiar_frame %>
    <%= f.input :apply_position %>
    <%= f.input :project_experience %>
    <%= f.input :self_evaluation %>
    <%= f.input :user_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
    <%= link_to '取消',resumes_path, class: 'button button-rounded button-flat' %>
  </div>
<% end %>

app/views/resumes/edit.html.erb
<h1>Editing Resume</h1>

<%= render 'form', resume: @resume %>

<%= link_to 'Show', @resume %> |
<%= link_to 'Back', resumes_path %>

app/views/resumes/index.html.erb
<table>
  <thead>
    <tr>
      <th><%= Resume.human_attribute_name(:personality) %></th>
      <th><%= Resume.human_attribute_name(:graduation_time) %></th>
      <th><%= Resume.human_attribute_name(:familiar_frame) %></th>
      <th><%= Resume.human_attribute_name(:apply_position) %></th>
      <th><%= Resume.human_attribute_name(:project_experience) %></th>
      <th><%= Resume.human_attribute_name(:self_evaluation) %></th>
      <th><%= Resume.human_attribute_name(:user_id) %></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @resumes.each do |resume| %>
      <tr>
        <td><%= resume.personality %></td>
        <td><%= resume.graduation_time %></td>
        <td><%= resume.familiar_frame %></td>
        <td><%= resume.apply_position %></td>
        <td><%= resume.project_experience %></td>
        <td><%= resume.self_evaluation %></td>
        <td><%= resume.user_id %></td>
        <td>
          <%= link_to 'Show', resume %>
          <%= link_to 'Edit', edit_resume_path(resume) %>
          <%= link_to 'Destroy', resume, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Resume', new_resume_path %>

app/views/resumes/new.html.erb
<h2>新增简历</h1>

<%= render 'form', resume: @resume %>

app/views/resumes/show.html.erb
<div>
    <table>
      <thead>
        <tr>
          <th style="width:30%;">属性</th>
          <th>值</th>
        </tr>
      </thead>

      <tbody>

        <tr>
          <th><%= Resume.human_attribute_name(:personality) %></th>
          <td><%= @resume.personality %></td>
        </tr>

        <tr>
          <th><%= Resume.human_attribute_name(:graduation_time) %></th>
          <td><%= @resume.graduation_time %></td>
        </tr>

        <tr>
          <th><%= Resume.human_attribute_name(:familiar_frame) %></th>
          <td><%= @resume.familiar_frame %></td>
        </tr>

        <tr>
          <th><%= Resume.human_attribute_name(:apply_position) %></th>
          <td><%= @resume.apply_position %></td>
        </tr>

        <tr>
          <th><%= Resume.human_attribute_name(:project_experience) %></th>
          <td><%= @resume.project_experience %></td>
        </tr>

        <tr>
          <th><%= Resume.human_attribute_name(:self_evaluation) %></th>
          <td><%= @resume.self_evaluation %></td>
        </tr>

        <tr>
          <th><%= Resume.human_attribute_name(:user_id) %></th>
          <td><%= @resume.user_id %></td>
        </tr>

      </tbody>
    </table>
<div>

<div class="other-actions">
  <%= link_to 'Edit', edit_resume_path(@resume) %> |
  <%= link_to 'Back', resumes_path %>
</div>